name: Build acbi-geth
on: 
 workflow_dispatch:
  inputs:
   version:
    description: 'geth binary version'
    required: true
    default: '1.0'
jobs:
  build_abci-geth:
    name: Build abci-geth
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/abci-geth
        submodules: recursive
    - name: Make
      run: make geth
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/bin/geth gs://${{ secrets.GCS_BUCKET }}/bin/geth-${{github.event.inputs.version}}-linux-amd64
