name: Build marlinctl
on: 
 workflow_dispatch:
  inputs:
   version:
    description: 'marlinctl version'
    required: true
    default: '1.0'
jobs:
  build_marlinctl:
    name: Build marlinctl
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/marlinctl
        submodules: recursive
    - uses: actions/setup-go@v2
    - name: Build
      run: go build -o build/marlinctl
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/marlinctl gs://${{ secrets.GCS_BUCKET }}/bin/marlinctl-linux-amd64
