name: Build marlinctl
on: 
 workflow_dispatch:
  inputs:
   version:
    description: 'marlinctl version'
    required: true
    default: '1.0'
jobs:
  build_marlinctl:
    name: Build marlinctl
    strategy:
      matrix:
       include:
        - os: 'ubuntu-18.04'
          build_type: Release
          GOOS: linux
          GOARCH: amd64
        - os: 'macos-latest'
          build_type: Release
          GOOS: darwin
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/marlinctl
        submodules: recursive
    - uses: actions/setup-go@v2
    - name: Build
      run: go build -o build/marlinctl
    - name: Upload
      run: |
       echo "marlinctl-${{matrix.GOOS}}-${{matrix.GOARCH}}"
