name: Build OpenWeaver
on:
  workflow_dispatch:
   inputs:
    beacon-version:
     description: 'beacon binary version'
     required: true
     default: '0.0.1'
    eth_relay-version:
     description: 'eth_relay binary version'
     required: true
     default: '0.0.1'
    gateway_eth-version:
     description: 'gateway_eth binary version'
     required: true
     default: '0.0.1'
    near_gateway-version:
     description: 'near_gateway binary version'
     required: true
     default: '0.0.1'
    iris_bridge-version:
     description: 'iris_bridge binary version'
     required: true
     default: '0.0.1'
jobs:
  build_openweaver_mac:
    name: Build openWeaver mac
    strategy:
      matrix:
        include:
        - os: 'macos-latest'
          build_type: Release
          GOOS: darwin
          GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: install brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install doxygen
      run: |
        brew install doxygen
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/OpenWeaver
        submodules: recursive
    - name: Build folder
      run: mkdir build
    - name: CMake
      run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Make
      run: cd build && make -j4
    - name: Tests
      run: cd build && ctest
    - name: Upload
      run: |
        echo "${{matrix.GOOS}}-${{matrix.GOARCH}}"

