name: Build OpenWeaver
on:
  workflow_dispatch:
   inputs:
    beacon-version:
     description: 'beacon binary version'
     required: true
     default: '0.0.1'
    eth_relay-version:
     description: 'eth_relay binary version'
     required: true
     default: '0.0.1'
    gateway_eth-version:
     description: 'gateway_eth binary version'
     required: true
     default: '0.0.1'
    near_gateway-version:
     description: 'gateway_eth binary version'
     required: true
     default: '0.0.1'
jobs:
  build_openweaver:
    name: Build openWeaver
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/OpenWeaver
        submodules: recursive
    - name: install doxygen
      run: sudo apt-get install doxygen
    - name: install graphviz dot
      run: sudo apt install graphviz
    - name: Build folder
      run: mkdir build
    - name: CMake
      run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Make
      run: cd build && make -j4
    - name: Tests
      run: cd build && ctest
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/beacon/beacon gs://${{ secrets.GCS_BUCKET }}/bin/beacon-${{github.event.inputs.beacon-version}}-linux-amd64
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/relay/eth_relay gs://${{ secrets.GCS_BUCKET }}/bin/eth_relay-${{github.event.inputs.eth_relay-version}}-linux-amd64
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/integrations/eth/onramp_eth gs://${{ secrets.GCS_BUCKET }}/bin/eth_gateway-${{github.event.inputs.gateway_eth-version}}-linux-amd64
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/integrations/near/near_gateway gs://${{ secrets.GCS_BUCKET }}/bin/near_gateway-${{github.event.inputs.near_gateway-version}}-linux-amd64
