name: Build tendermint_connector
on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'tendermint_connector version'
        required: true
        default: '0.1-alpha'
jobs:
  build_tendermint_connector:
    name: Build tendermint_connector
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        repository: supragya/TendermintConnector
    - uses: actions/setup-go@v2
    - name: Build tendermint_connector
      run: make
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/tendermint_connector gs://${{ secrets.GCS_BUCKET }}/bin/tendermint_connector-linux-amd64
