name: Build tendermint_connector
on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'tendermint_connector version'
        required: true
        default: '0.1-alpha'
jobs:
  build_tendermint_connector:
    name: Build tendermint_connector
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2
    - name: Install Protobuf Compiler
      uses: arduino/setup-protoc@v1
    - name: Install protoc-gen-go for proto3 golang support
      run: go get github.com/golang/protobuf/protoc-gen-go && export PATH="$PATH:$(go env GOPATH)/bin"
    - name: Pull Codebase Tendermint Connector
      uses: actions/checkout@v2
      with:
        ref: main
        repository: supragya/TendermintConnector
    - name: Build tendermint_connector
      run: make
    - name: Google Cloud Utilities Setup
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload Build artifact (tendermint_connector) to Google Cloud
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/tendermint_connector gs://${{ secrets.GCS_BUCKET }}/bin/tendermint_connector-${{github.event.inputs.beacon-version}}-linux-amd64
