name: Build tendermint_connector
on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'tendermint_connector version'
        required: true
        default: '0.1-alpha'
jobs:
  build_tendermint_connector:
    name: Build tendermint_connector
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Pull Codebase Protobuf
      uses: actions/checkout@v2
      with:
        ref: master
        repository: google/protobuf
        submodules: recursive
    - name: (1) Protobuf Autogen
      run: sh autogen.sh
    - name: (2) Protobuf make
      run: pwd && make
    - name: (3) Protobuf make check
      run: make check
    - name: (4) Protobuf make install
      run: sudo make install
    - name: Setup Go
      uses: actions/setup-go@v2
    - name: Pull Codebase Tendermint Connector
      uses: actions/checkout@v2
      with:
        ref: main
        repository: supragya/TendermintConnector
    - name: Build Tendermint Connector
      run: make
    - name: Google Cloud Utilities Setup
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload artifact to Google Cloud
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/tendermint_connector gs://${{ secrets.GCS_BUCKET }}/bin/tendermint_connector-linux-amd64
