name: Test
on: 
 workflow_dispatch:
jobs:
  test-os:
    name: test Os
    strategy:
      matrix:
        os: ['macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 10.3
    - name: run command
      run: gcc --version
