name: Test
on: 
 workflow_dispatch:
jobs:
  test-os:
    name: test Os
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: run command
      run: gcc --version
      
