name: Upload supervisor-conf
on: 
 workflow_dispatch:
jobs:
  upload-conf:
    name: Upload conf
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/marlinctl
        submodules: recursive
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Upload
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp configs/*.conf gs://${{ secrets.GCS_BUCKET }}/configs
